classdef ScriptHoleTab < handle
    properties
        Name
        ConstructionGroup;
        Script;
    end
    
    methods
        function obj = ScriptHoleTab(name)
            if nargin == 0
                obj.Name = 'trunc_cone';
                obj.ConstructionGroup = 1;
                obj.Script = strcat(['deleteall;\n r_top = %%r top%%;\n r_bottom = %%r bottom%%;\n z_span = %%z span%%;\n'...
                    'r_top = r_top +1e-20;\n ?theta=atan((r_bottom-r_top)/z_span);\n'...
                    '?ht=r_top/tan(theta);\n addcustom;\nset("x",0);\n set("y",0);\nset("z",0);\n'...
                    'set("first axis","y");\n set("rotation 1",90);\n'...
                    ' set("x span",z_span);\n set("y span",2*max([r_bottom, r_top]));\n'...
                    'set("z span",2*max([r_bottom, r_top]));\n set("name","cone");\n'...
                    'set("create 3D object by","revolution");\n',...
                    '?eqn = num2str(r_top/ht)+"*(x+"+num2str((z_span/2+ht)*1e6)+")";\n'...
                    'set("equation 1",eqn);\n',...
                    'set("material",material);\n if(get("material")=="<Object defined dielectric>")'...
                    '{ set("index",index);}']);
            else
                obj.Name = name;
                obj.ConstructionGroup = 1;
                obj.Script = strcat(['deleteall; r_top = rtop; r_bottom = rbottom; z_span = zspan;'...
                    'r_top = r_top +1e-20; ?theta=atan((r_bottom-r_top)/z_span);'...
                    '?ht=r_top/tan(theta); addcustom;set("x",0); set("y",0);set("z",0);'...
                    'set("first axis","y"); set("rotation 1",90);'...
                    ' set("x span",z_span); set("y span",2*max([r_bottom, r_top]));'...
                    'set("z span",2*max([r_bottom, r_top])); set("name","cone");',...
                    'set("create 3D object by","revolution");',...
                    '?eqn = num2str(r_top/ht)+"*(x+"+num2str((z_span/2+ht)*1e6)+")";',...
                    'set("equation 1",eqn);',...
                    'set("material",material);if(get("material")=="<Object defined dielectric>")',...
                    '{ set("index",index);}']);
            end
        end
        
        function set.ConstructionGroup(obj, constructionGroup)
            obj.ConstructionGroup = set_check_box(constructionGroup);
        end   
    end
    
    methods(Static)
        test();
    end
end